# Generated by Django 5.1.7 on 2025-07-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_url_transaction_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fileName',
        ),
    ]
